;
; Defaults
;

[env]
extends = core
lib_compat_mode = strict
build_flags =
lib_deps =
  SPI
  Wire

[defaults]
hardware.neopixel = false
option.core.sms.adapter = all
option.core.gg.adapter = all
option.core.sg1000.adapter = all

arch.build_src_flags =
arch.build_flags =
arch.extra_scripts =
arch.lib_deps =

mcu.build_src_flags =
mcu.build_flags =
mcu.extra_scripts =
mcu.lib_deps =

board.build_src_flags =
board.build_flags =
board.extra_scripts =
board.lib_deps =

output.build_src_flags =
output.build_flags =
output.extra_scripts =
output.lib_deps =

output.serial_type = ASCII
output.lcd_type =

input.build_src_flags =
input.build_flags =
input.extra_scripts =
input.lib_deps =
