;
; Final Hardware Environments
;

[env:HardwareV5]
extends =
  board:mega-embed
  hardware:5
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}


[env:HardwareV4]
extends =
  board:mega-embed
  hardware:4
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}


[env:HardwareV3]
extends =
  board:mega-embed
  hardware:3
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:HardwareV2]
extends =
  board:mega-embed
  hardware:2
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:HardwareV1]
extends =
  board:mega-embed
  hardware:1
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:SerialASCII]
extends =
  board:mega-embed
  hardware:serial:ascii
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}



[env:SerialANSI]
extends =
  board:mega-embed
  hardware:serial:ansi
build_src_flags =
  ${this.arch.build_src_flags}
  ${this.mcu.build_src_flags}
  ${this.board.build_src_flags}
  ${this.output.build_src_flags}
  ${this.input.build_src_flags}
  -D HW_VERSION=${this.hardware.version}
build_flags =
  ${this.arch.build_flags}
  ${this.mcu.build_flags}
  ${this.board.build_flags}
  ${this.output.build_flags}
  ${this.input.build_flags}
extra_scripts =
  ${this.arch.extra_scripts}
  ${this.mcu.extra_scripts}
  ${this.board.extra_scripts}
  ${this.output.extra_scripts}
  ${this.input.extra_scripts}
lib_deps =
  ${this.arch.lib_deps}
  ${this.mcu.lib_deps}
  ${this.board.lib_deps}
  ${this.output.lib_deps}
  ${this.input.lib_deps}
